services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: CounterStrikeItemsApi/Dockerfile
    container_name: main_api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:8080"
    env_file:
      - .env.docker

  web:
    build:
      context: .
      dockerfile: WebAdminPanel/Dockerfile
    container_name: web_admin_panel
    restart: always
    depends_on:
      - api
    ports:
      - "5001:80"

  worker:
    build:
      context: .
      dockerfile: WorkerHost/Dockerfile
    container_name: background_workerhost
    restart: always
    depends_on:
      - postgres
      - redis
      - api
    env_file:
      - .env.docker

volumes:
  postgres_data:
  redis_data:
